### PR TITLE
Fix the issue where dropping a send request future de-syncs the client and server

### LINKED ISSUE #20: Async request sending can be interrupted, causing the connection to go out of sync with respect to packet boundaries
This is what I actually wanted to test when I ran into #19. The following is tested with my hack/patch from https://github.com/not-a-seagull/breadx/issues/19#issuecomment-757113660 to make async request sending actually work with partial writes.

This is the same example as in #19, but extended with a timeout. You might have to "play" a bit with the timeout value to make this break.

The idea is to send a big request with a timeout. The timeout should fire "in the middle" of request sending, so that the request was only sent partially. Since the timeout causes the request sending future to be just dropped, nothing can send the rest of the request. Thus, the partial write is never resolved and the X11 server cannot figure out where the next request begins (since it still expects more data from the last request).
```rust
use std::time::Duration;
use breadx::{DisplayConnection, ImageFormat, Image, drawable };
use smol::{Executor, Timer, future::race};

// async entry point
async fn entry() -> breadx::Result<()> {
    const WIDTH: usize = 997;
    const HEIGHT: usize = 1009;
    const MEMORY: [u8; WIDTH * HEIGHT * 4] = [0; WIDTH * HEIGHT * 4];

    let mut conn = DisplayConnection::create_async(None, None).await?;
    let image = Image::new(
        &conn,
        None,
        24,
        ImageFormat::ZPixmap,
        0,
        &MEMORY[..],
        WIDTH,
        HEIGHT,
        32,
        None,
    ).unwrap();
    let root = conn.default_root();
    let gc = conn.create_gc(root, Default::default())?;
    let pixmap = drawable::create_pixmap(&mut conn, root, WIDTH as _, HEIGHT as _, 24)?;
    for _ in 0..10 {
        let put = async {
            drawable::put_image_async(
                &mut conn,
                pixmap,
                gc,
                &image,
                0,
                0,
                0,
                0,
                WIDTH as _,
                HEIGHT as _,
            ).await.unwrap();
            "PutImage"
        };
        let timeout = async {
            Timer::after(Duration::from_millis(5)).await;
            "timeout"
        };
        println!("{:?}", race(put, timeout).await);
    }
    Ok(())
}

fn main() -> breadx::Result<()> {
    //std::env::set_var("RUST_LOG", "breadx=trace");
    env_logger::init();
    let ex = Executor::new();
    async_io::block_on(ex.run(entry())).unwrap();
    Ok(())
}
```
Under `xtrace` (and built with `--release`) this shows symptoms of the problem I described above:
```
000:<:0002: 16: Request(53): CreatePixmap depth=0x18 pid=0x02000002 drawable=0x00000761 width=997 height=1009
000:<: Warning: buffer filled!
000:<:0003:259244: Request(72): PutImage format=ZPixmap(0x02) drawable=0x02000002 gc=0x02000001 width=997 height=65 dst-x=0 dst-y=0 left-pad=0x00 depth=0x18
000:<: Warning: buffer filled!
000:<:0004:259244: Request(72): PutImage format=ZPixmap(0x02) drawable=0x02000002 gc=0x02000001 width=997 height=65 dst-x=0 dst-y=65 left-pad=0x00 depth=0x18
000:<: Warning: buffer filled!
000:<:0005:259244: Request(72): PutImage format=ZPixmap(0x02) drawable=0x02000002 gc=0x02000001 width=997 height=65 dst-x=0 dst-y=130 left-pad=0x00 depth=0x18
000:<: Warning: buffer filled!
000:<:0006:259244: Request(72): PutImage format=ZPixmap(0x02) drawable=0x02000002 gc=0x02000001 width=997 height=65 dst-x=0 dst-y=195 left-pad=0x00 depth=0x18
000:<: Warning: buffer filled!
000:<:0007:259244: Request(72): PutImage format=ZPixmap(0x02) drawable=0x02000002 gc=0x02000001 width=997 height=65 dst-x=0 dst-y=260 left-pad=0x00 depth=0x18
000:<: Warning: buffer filled!
000:<:0008:259244: Request(72): PutImage format=ZPixmap(0x02) drawable=0x02000002 gc=0x02000001 width=997 height=65 dst-x=0 dst-y=325 left-pad=0x00 depth=0x18
000:<: Warning: buffer filled!
000:<:0009:259244: Request(72): PutImage format=ZPixmap(0x02) drawable=0x02000002 gc=0x02000001 width=997 height=65 dst-x=0 dst-y=390 left-pad=0x00 depth=0x18
000:<: Warning: buffer filled!
000:<:000a:259244: Request(72): PutImage format=ZPixmap(0x02) drawable=0x02000002 gc=0x02000001 width=997 height=65 dst-x=0 dst-y=455 left-pad=0x00 depth=0x18
"timeout"
000:<:000b:  0: Request(0): UNKNOWN   
000:<: Warning: buffer filled!
000:<:000c:  0: Request(0): UNKNOWN   
"timeout"
"timeout"
```
When changing the value of `MEMORY` from 0 to 42, xtrace suddenly sees lots and lots of `SetInputFocus` requests.

### PR DESCRIPTION
**Pull request by not-a-seagull**
This pull request resolves #20 and fixes the issue where dropping the send request future would cause a de-sync between the client and server. It accomplishes this by taking the nuclear option: marking the connection as tainted and preventing bytes from being sent down it or read from it again. Note that this could also occur with the `wait_async` future, but that would require fine-tuning the future a little to ensure dropping during the "wait" period doesn't taint the display.

### CODE REVIEW

**Comment by not-a-seagull** [comment]
Note that this also has a few things I developed in an offstream branch, like special event queues, that I forgot the merge into master until now.

File: src/display/connection/unix.rs [hunk 1]
```diff
@@ -51,7 +53,7 @@ fn send_msg_packet(conn: RawFd, data: &[u8], fds: &mut Vec<Fd>) -> io::Result<()
         sendmsg_loop(conn, data, &cmsgs)
     };
 
-    if res.is_ok() {
+    if res.1.is_ok() {
         fds.clear();
```
Comment (psychon) [inline src/display/connection/unix.rs:57]: Hey @not-a-seagull it occurred to me that my patch has a bug here with FD sending (well... or rather "there was a bug here before that my patch did not fix"? Your call).

The above `res.1.is_ok()` clears `fds` when sending was successful. But there could also have been a partial send. Thus, I think this now needs to be `offset > 0`. Otherwise, the retry of the sending will re-send the FDs again.
